apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: bridge.mediaconnect.aws.livewyer.io
spec:
  compositeTypeRef:
    apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
    kind: Bridge
  mode: Pipeline
  pipeline:
    - step: go-templating
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{ $id := .observed.composite.resource.metadata.name -}}
            {{ $spec := .observed.composite.resource.spec.forProvider -}}

            apiVersion: cloudcontrol.aws.m.upbound.io/v1beta1
            kind: Resource
            metadata:
              name: {{ $id }}
              namespace: {{ default "default" $.observed.composite.resource.metadata.namespace }}
              annotations:
                {{ setResourceNameAnnotation (printf "bridge.mediaconnect.aws.livewyer.io/%s" $id) }}
              labels:
                mediaconnect.aws.livewyer.io/bridge: {{ $id }}
            spec:
            {{- if .observed.composite.resource.spec.providerConfigRef }}
              providerConfigRef:
            {{ toYaml .observed.composite.resource.spec.providerConfigRef | indent 4 }}
            {{- end }}
            {{- if .observed.composite.resource.spec.deletionPolicy }}
              deletionPolicy: {{ .observed.composite.resource.spec.deletionPolicy }}
            {{- end }}
            {{- if .observed.composite.resource.spec.managementPolicies }}
              managementPolicies:
            {{ toYaml .observed.composite.resource.spec.managementPolicies | indent 4 }}
            {{- end }}
            {{- if .observed.composite.resource.spec.publishConnectionDetailsTo }}
              publishConnectionDetailsTo:
            {{ toYaml .observed.composite.resource.spec.publishConnectionDetailsTo | indent 4 }}
            {{- end }}
            {{- if .observed.composite.resource.spec.writeConnectionSecretsToNamespace }}
              writeConnectionSecretsToNamespace: {{ .observed.composite.resource.spec.writeConnectionSecretsToNamespace }}
            {{- end }}
              forProvider:
                region: {{ $spec.region }}
                typeName: AWS::MediaConnect::Bridge
                desiredState: |-
                  {
                    "Name": "{{ $id }}",
                    "PlacementArn": "{{ $spec.placementArn }}"
                    {{- if $spec.sources }},
                    "Sources": {{ toJson $spec.sources }}
                    {{- end }}
                    {{- if $spec.outputs }},
                    "Outputs": {{ toJson $spec.outputs }}
                    {{- end }}
                    {{- if $spec.egressGatewayBridge }},
                    "EgressGatewayBridge": {{ toJson $spec.egressGatewayBridge }}
                    {{- end }}
                    {{- if $spec.ingressGatewayBridge }},
                    "IngressGatewayBridge": {{ toJson $spec.ingressGatewayBridge }}
                    {{- end }}
                    {{- if $spec.sourceFailoverConfig }},
                    "SourceFailoverConfig": {{ toJson $spec.sourceFailoverConfig }}
                    {{- end }}
                    {{- if $spec.tags }},
                    "Tags": {{ toJson $spec.tags }}
                    {{- end }}
                  }

            ---

            {{ $awscc := getComposedResource . (printf "bridge.mediaconnect.aws.livewyer.io/%s" $id) }}
            apiVersion: {{ .observed.composite.resource.apiVersion }}
            kind: {{ .observed.composite.resource.kind }}
            metadata:
              labels:
                mediaconnect.aws.livewyer.io/bridge: {{ $id }}
            status:
              atProvider: {{ toJson $awscc.status.atProvider }}

    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: function-auto-ready
