apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: workflowtemplate.elemental.aws.livewyer.io
spec:
  compositeTypeRef:
    apiVersion: elemental.aws.livewyer.io/v1alpha1
    kind: WorkflowTemplate
  mode: Pipeline
  pipeline:
    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: function-auto-ready
