apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: channelgroup.mediapackagev2.aws.livewyer.io
spec:
  compositeTypeRef:
    apiVersion: mediapackagev2.aws.livewyer.io/v1alpha1
    kind: XChannelGroup
  mode: Pipeline
  pipeline:
    - step: go-templating
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{ $id := .observed.composite.resource.metadata.name -}}
            {{ $spec := .observed.composite.resource.spec.parameters -}}

            apiVersion: cloudcontrol.aws.upbound.io/v1beta1
            kind: Resource
            metadata:
              name: {{ $id }}
              annotations:
                {{ setResourceNameAnnotation (printf "channelgroup.mediapackagev2.aws.livewyer.io/%s" $id) }}
              labels:
                mediapackagev2.aws.livewyer.io/channelgroup: {{ $id }}
            spec:
            {{- if .observed.composite.resource.spec.providerConfigRef }}
              providerConfigRef:
            {{ toYaml .observed.composite.resource.spec.providerConfigRef | indent 4 }}
            {{- end }}
            {{- if .observed.composite.resource.spec.deletionPolicy }}
              deletionPolicy: {{ .observed.composite.resource.spec.deletionPolicy }}
            {{- end }}
            {{- if .observed.composite.resource.spec.managementPolicies }}
              managementPolicies:
            {{ toYaml .observed.composite.resource.spec.managementPolicies | indent 4 }}
            {{- end }}
            {{- if .observed.composite.resource.spec.publishConnectionDetailsTo }}
              publishConnectionDetailsTo:
            {{ toYaml .observed.composite.resource.spec.publishConnectionDetailsTo | indent 4 }}
            {{- end }}
            {{- if .observed.composite.resource.spec.writeConnectionSecretsToNamespace }}
              writeConnectionSecretsToNamespace: {{ .observed.composite.resource.spec.writeConnectionSecretsToNamespace }}
            {{- end }}
              forProvider:
                typeName: AWS::MediaPackageV2::ChannelGroup
                region: {{ $spec.region }}
                desiredState: |-
                  {
                    "ChannelGroupName": "{{ $spec.channelGroupName }}"
                    {{- if $spec.description }},
                    "Description": "{{ $spec.description }}"
                    {{- end }}
                    {{- if $spec.tags }},
                    "Tags": {{ toJson $spec.tags }}
                    {{- end }}
                  }

            ---

            {{ $awscc := getComposedResource . (printf "channelgroup.mediapackagev2.aws.livewyer.io/%s" $id) }}
            apiVersion: {{ .observed.composite.resource.apiVersion }}
            kind: {{ .observed.composite.resource.kind }}
            metadata:
              labels:
                mediapackagev2.aws.livewyer.io/channelgroup: {{ $id }}
            status:
              atProvider: {{ toJson $awscc.status.atProvider }}

    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: function-auto-ready
