apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: channels.mediapackagev2.aws.livewyer.io
spec:
  scope: Namespaced
  group: mediapackagev2.aws.livewyer.io
  names:
    kind: Channel
    plural: channels
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                forProvider:
                  type: object
                  properties:
                    channelGroupName:
                      type: string
                      description: "The name of the channel group associated with the channel configuration."
                      pattern: "^[a-zA-Z0-9_-]+$"
                      minLength: 1
                      maxLength: 256
                    description:
                      type: string
                      description: "The description of the channel."
                      minLength: 0
                      maxLength: 1024
                    inputType:
                      type: string
                      description: "The input type will be an immutable field which will be used to define whether the channel will allow CMAF ingest or HLS ingest."
                      enum:
                        - "HLS"
                        - "CMAF"
                      default: "HLS"
                    inputSwitchConfiguration:
                      type: object
                      description: "The configuration for input switching based on the media quality confidence score (MQCS) as provided from AWS Elemental MediaLive."
                      properties:
                        MQCSInputSwitching:
                          type: boolean
                          description: "When true, AWS Elemental MediaPackage performs input switching based on the MQCS. Default is true. This setting is valid only when InputType is CMAF."
                    outputHeaderConfiguration:
                      type: object
                      description: "The settings for what common media server data (CMSD) headers AWS Elemental MediaPackage includes in responses to the CDN."
                      properties:
                        PublishMQCS:
                          type: boolean
                          description: "When true, AWS Elemental MediaPackage includes the MQCS in responses to the CDN. This setting is valid only when InputType is CMAF."
                    region:
                      type: string
                      description: "AWS region where the channel will be created."
                    tags:
                      type: object
                      description: "A map of tags to assign to the resource."
                      additionalProperties:
                        type: string
                  required:
                    - channelGroupName
                deletionPolicy:
                  type: string
                  enum:
                    - Delete
                    - Orphan
                  default: Delete
                  description: "DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted."
                managementPolicies:
                  type: array
                  items:
                    type: string
                    enum:
                      - "*"
                      - Create
                      - Update
                      - Delete
                      - LateInitialize
                      - Observe
                  default: ["*"]
                  description: "ManagementPolicies specify the array of actions Crossplane is allowed to take on the managed and external resources."
                providerConfigRef:
                  type: object
                  properties:
                    name:
                      type: string
                  required:
                    - name
                  description: "ProviderConfigReference specifies how the provider that will be used to create, observe, update, and delete this managed resource should be configured."
                publishConnectionDetailsTo:
                  type: object
                  properties:
                    name:
                      type: string
                    configRef:
                      type: object
                      properties:
                        name:
                          type: string
                      required:
                        - name
                    metadata:
                      type: object
                      properties:
                        labels:
                          type: object
                          additionalProperties:
                            type: string
                        annotations:
                          type: object
                          additionalProperties:
                            type: string
                        type:
                          type: array
                          items:
                            type: string
                  required:
                    - name
                  description: "PublishConnectionDetailsTo specifies the connection secret config which contains a name, metadata and a reference to secret store config to which any connection details for this managed resource should be written."
                writeConnectionSecretsToNamespace:
                  type: string
                  description: "WriteConnectionSecretsToNamespace specifies the namespace in which the connection secrets of this managed resource should be written."
              required:
                - forProvider
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      lastTransitionTime:
                        type: string
                        format: date-time
                      message:
                        type: string
                      reason:
                        type: string
                      status:
                        type: string
                      type:
                        type: string
                    required:
                      - lastTransitionTime
                      - reason
                      - status
                      - type
                connectionDetails:
                  type: object
                  properties:
                    lastPublishedTime:
                      type: string
                      format: date-time
                atProvider:
                  type: object
                  description: "Porvider state."
                  x-kubernetes-preserve-unknown-fields: true
          required:
            - spec
