apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: workflow.elemental.aws.livewyer.io
spec:
  compositeTypeRef:
    apiVersion: elemental.aws.livewyer.io/v1alpha1
    kind: XWorkflow
  mode: Pipeline
  pipeline:
    - step: go-templating
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{- define "setNestedValue" -}}
            {{- $dict := index . 0 -}}
            {{- $path := index . 1 -}}
            {{- $value := index . 2 -}}
            {{- $parts := regexSplit "\\." $path -1 -}}
            {{- if eq (len $parts) 1 -}}
              {{- $_ := set $dict (first $parts) $value -}}
            {{- else -}}
              {{- $firstKey := first $parts -}}
              {{- $remainingParts := rest $parts -}}
              {{- $remainingPath := join "." $remainingParts -}}
              {{- if not (hasKey $dict $firstKey) -}}
                {{- $_ := set $dict $firstKey (dict) -}}
              {{- end -}}
              {{- template "setNestedValue" (list (index $dict $firstKey) $remainingPath $value) -}}
            {{- end -}}
            {{- end -}}

            {{- range $step := .observed.composite.resource.spec.steps }}
            {{- range $resource := $step.resources }}
            {{- $spec := (dig "spec" (dict) $resource.spec) }}
            {{- $parameters := (dig "spec" "forProvider" dict $resource.spec) }}

            ---

            apiVersion: {{ $resource.spec.apiVersion }}
            kind: {{ $resource.spec.kind }}
            metadata:
              name: {{ $resource.name }}
              namespace: {{ default "default" $.observed.composite.resource.metadata.namespace }}
              annotations:
                {{ setResourceNameAnnotation (regexReplaceAll "(.*)/(.*)" $resource.spec.apiVersion (printf "%s.${1}/%s" ($resource.spec.kind | lower) $resource.name)) }}
              labels:
                elemental.aws.livewyer.io/workflow: {{ $.observed.composite.resource.metadata.name }}
                {{ regexReplaceAll "(.*)/(.*)" $resource.spec.apiVersion (printf "${1}/%s" $resource.spec.kind | lower) }}: {{ $resource.name }}
            spec:
            {{- if $spec.providerConfigRef }}
              providerConfigRef:
            {{ toYaml $spec.providerConfigRef | indent 4 }}
            {{- else }}
              providerConfigRef:
            {{ toYaml $.observed.composite.resource.spec.providerConfigRef | indent 4 }}
            {{- end }}
            {{- if $spec.deletionPolicy }}
              deletionPolicy: {{ $spec.deletionPolicy }}
            {{- end }}
            {{- if $spec.managementPolicies }}
              managementPolicies:
            {{ toYaml $spec.managementPolicies | indent 4 }}
            {{- end }}
            {{- if $spec.publishConnectionDetailsTo }}
              publishConnectionDetailsTo:
            {{ toYaml $spec.publishConnectionDetailsTo | indent 4 }}
            {{- end }}
            {{- if $spec.writeConnectionSecretsToNamespace }}
              writeConnectionSecretsToNamespace: {{ $spec.writeConnectionSecretsToNamespace }}
            {{- end }}
              forProvider:
            {{- if not $parameters.region }}
            {{- template "setNestedValue" (list $parameters "region" $.observed.composite.resource.spec.forProvider.region) }}
            {{- end }}
            {{- range $depend := (default list $resource.dependsOn) }}
            {{- template "setNestedValue" (list $parameters $depend.key (dig "resources" (regexReplaceAll "(.*)/(.*)" $depend.source.apiVersion (printf "%s.${1}/%s" ($depend.source.kind | lower) $depend.source.name)) "resource" "status" "atProvider" "id" "" $.observed)) }}
            {{- end }}
            {{ toYaml $parameters | indent 4 }}

            {{- end }}
            {{- end }}

    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: function-auto-ready
