apiVersion: medialive.aws.livewyer.io/v1alpha1
kind: Network
metadata:
  name: network-test
  labels:
    mediaconnect.aws.livewyer.io/network: network-test
spec:
  providerConfigRef:
    name: aws
  forProvider:
    region: us-east-1
    ipPools:
      - Cidr: 192.168.254.10/32
