apiVersion: elemental.aws.livewyer.io/v1alpha1
kind: XWorkflow
metadata:
  name: workflow-demo
  labels:
    elemental.aws.livewyer.io/workflow: workflow-demo
spec:
  providerConfigRef:
    name: aws
  forProvider:
    region: us-east-1
  steps:
    - name: mediaconnect-flow
      resources:
        - name: mediaconnect-flow-a
          spec:
            apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
            kind: XFlow
            spec:
              forProvider:
                flowSize: MEDIUM
                source:
                  Name: onprem-source-a
                  WhitelistCidr: 192.168.0.100/32
                  IngestPort: 3000
                  Protocol: rtp
                  MaxBitrate: 100000
        - name: mediaconnect-flow-b
          spec:
            apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
            kind: XFlow
            spec:
              forProvider:
                flowSize: MEDIUM
                source:
                  Name: onprem-source-b
                  WhitelistCidr: 192.168.0.100/32
                  IngestPort: 4000
                  Protocol: rtp
                  MaxBitrate: 100000

    - name: medialive-network
      resources:
        - name: medialive-network-sg
          spec:
            apiVersion: medialive.aws.upbound.io/v1beta1
            kind: InputSecurityGroup
            spec:
              forProvider:
                whitelistRules:
                  - cidr: 192.168.0.100/32

    - name: medialive-input
      resources:
        - name: medialive-input-a
          dependsOn:
            - key: mediaConnectFlows
              type: list
              subKey: flowArn
              source:
                name: mediaconnect-flow-a
                apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
                kind: XFlow
                key: status.atProvider.id
            - key: mediaConnectFlows
              type: list
              subKey: flowArn
              source:
                name: mediaconnect-flow-b
                apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
                kind: XFlow
                key: status.atProvider.id
          spec:
            apiVersion: medialive.aws.upbound.io/v1beta2
            kind: Input
            spec:
              forProvider:
                name: medialive-input-a
                inputSecurityGroups:
                  - medialive-network-sg
                type: MEDIACONNECT
                roleArn: arn:aws:iam::627399506400:role/MediaLiveAccessRole
        - name: medialive-input-b
          dependsOn:
            - key: mediaConnectFlows
              type: list
              subKey: flowArn
              source:
                name: mediaconnect-flow-a
                apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
                kind: XFlow
                key: status.atProvider.id
            - key: mediaConnectFlows
              type: list
              subKey: flowArn
              source:
                name: mediaconnect-flow-b
                apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
                kind: XFlow
                key: status.atProvider.id
          spec:
            apiVersion: medialive.aws.upbound.io/v1beta2
            kind: Input
            spec:
              forProvider:
                name: medialive-input-b
                inputSecurityGroups:
                  - medialive-network-sg
                type: MEDIACONNECT
                roleArn: arn:aws:iam::627399506400:role/MediaLiveAccessRole

    - name: mediapackage-channel
      resources:
        - name: mediapackage-channel
          spec:
            apiVersion: mediapackage.aws.upbound.io/v1beta1
            kind: Channel
            spec:
              forProvider:
                channelId: mediapackage-channel
        - name: mediapackage-channel-endpoint
          spec:
            apiVersion: mediapackage.aws.livewyer.io/v1alpha1
            kind: XOriginEndpoint
            spec:
              forProvider:
                channelId: mediapackage-channel
                origination: ALLOW
                cmafPackage:
                  HlsManifests:
                    - Id: hls-manifest

    - name: medialive-channel
      resources:
        - name: medialive-channel-a
          spec:
            apiVersion: medialive.aws.upbound.io/v1beta2
            kind: Channel
            spec:
              forProvider:
                name: medialive-channel-a
                channelClass: STANDARD
                roleArn: arn:aws:iam::627399506400:role/MediaLiveAccessRole
                inputSpecification:
                  codec: AVC
                  inputResolution: SD
                  maximumBitrate: MAX_10_MBPS
                inputAttachments:
                  - inputAttachmentName: medialive-input-a
                    inputIdRef:
                      name: medialive-input-a
                    inputSettings:
                      captionSelector:
                        - name: sample-caption
                          languageCode: EN
                          selectorSettings:
                            embeddedSourceSettings: {}
                  - inputAttachmentName: medialive-input-b
                    inputIdRef:
                      name: medialive-input-b
                    inputSettings:
                      captionSelector:
                        - name: sample-caption
                          languageCode: EN
                          selectorSettings:
                            embeddedSourceSettings: {}
                destinations:
                  - id: mediapackage
                    mediaPackageSettings:
                      - channelId: mediapackage-channel
                  - id: s3
                    settings:
                      - url: s3://heron-prototype/live/recording-a
                      - url: s3://heron-prototype/live/recording-b
                encoderSettings:
                  outputGroups:
                    - name: mediapackage-output
                      outputGroupSettings:
                        mediaPackageGroupSettings:
                          destination:
                            destinationRefId: mediapackage
                      outputs:
                        - outputName: mediapackage-output
                          videoDescriptionName: sample-video
                          audioDescriptionNames:
                            - sample-audio
                          captionDescriptionNames:
                            - sample-caption
                          outputSettings:
                            mediaPackageOutputSettings: {}
                    - name: s3-output
                      outputGroupSettings:
                        archiveGroupSettings:
                          - destination:
                              destinationRefId: s3
                      outputs:
                        - outputName: s3-output
                          videoDescriptionName: sample-video
                          audioDescriptionNames:
                            - sample-audio
                          captionDescriptionNames:
                            - sample-caption
                          outputSettings:
                            archiveOutputSettings:
                              containerSettings:
                                m2tsSettings: {}
                              extension: m2ts
                              nameModifier: _1
                  timecodeConfig:
                    source: EMBEDDED
                  videoDescriptions:
                    - name: sample-video
                      height: 640
                      width: 480
                      scalingBehavior: DEFAULT
                      codecSettings:
                        h264Settings:
                          level: H264_LEVEL_AUTO
                          profile: MAIN
                          framerateControl: SPECIFIED
                          framerateDenominator: 1
                          framerateNumerator: 24
                          parControl: SPECIFIED
                          parDenominator: 3
                          parNumerator: 4
                  audioDescriptions:
                    - name: sample-audio
                      audioSelectorName: sample-audio
                  captionDescriptions:
                    - name: sample-caption
                      languageCode: EN
                      captionSelectorName: sample-caption
                      destinationSettings:
                        embeddedDestinationSettings: {}
