apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
kind: Flow
metadata:
  name: flow-test-a
  labels:
    mediaconnect.aws.livewyer.io/flow: flow-test-a
spec:
  providerConfigRef:
    kind: ProviderConfig
    name: aws
  forProvider:
    region: us-east-1
    flowSize: MEDIUM
    source:
      Name: source-a
      WhitelistCidr: 192.168.0.100/32
      IngestPort: 3000
      Protocol: rtp
      MaxBitrate: 100000

---
apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
kind: Flow
metadata:
  name: flow-test-b
  labels:
    mediaconnect.aws.livewyer.io/flow: flow-test-b
spec:
  providerConfigRef:
    kind: ProviderConfig
    name: aws
  forProvider:
    region: us-east-1
    flowSize: MEDIUM
    source:
      Name: onprem-source-b
      WhitelistCidr: 192.168.0.100/32
      IngestPort: 4000
      Protocol: rtp
    sourceMonitoringConfig:
      ThumbnailState: ENABLED
