apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
kind: Flow
metadata:
  name: flow-test-a
  labels:
    mediaconnect.aws.livewyer.io/flow: flow-test
spec:
  providerConfigRef:
    name: aws
  forProvider:
    region: us-east-1
    flowSize: MEDIUM
    source:
      GatewayBridgeSource:
        BridgeArn: ""
