apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
kind: Gateway
metadata:
  name: mediaconnect-gateway-a
  labels:
    mediaconnect.aws.livewyer.io/gateway: mediaconnect-gateway-a
spec:
  providerConfigRef:
    kind: ProviderConfig
    name: aws
  forProvider:
    region: us-east-1
    egressCidrBlocks:
      - 10.10.0.100
    networks:
      - Name: source
        CidrBlock: 10.10.0.100
