apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-aws-elemental-admin
rules:
  - apiGroups:
      - aws.upbound.io
      - aws.livewyer.io
    resources:
      - "*"
    verbs:
      - "*"
  # - apiGroups:
  #     - ""
  #   resources:
  #     - services
  #     - configmaps
  #   verbs:
  #     - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane-aws-elemental-admin
subjects:
  - kind: ServiceAccount
    name: crossplane
    namespace: crossplane-system
roleRef:
  kind: ClusterRole
  name: cluster-aws-elemental-admin
  apiGroup: rbac.authorization.k8s.io
