apiVersion: elemental.aws.livewyer.io/v1alpha1
kind: XWorkflow
metadata:
  name: workflow-test
  labels:
    elemental.aws.livewyer.io/workflow: workflow-test
spec:
  providerConfigRef:
    name: aws
  forProvider:
    region: us-east-1
  steps:
    - name: mediaconnect-gateway
      resources:
        - name: mediaconnect-gateway-a
          spec:
            apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
            kind: XGateway
            spec:
              forProvider:
                egressCidrBlocks:
                  - 88.98.197.180/32
                networks:
                  - Name: onprem-a
                    CidrBlock: 88.98.197.180/32
        - name: mediaconnect-gateway-b
          spec:
            apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
            kind: XGateway
            spec:
              forProvider:
                egressCidrBlocks:
                  - 88.98.197.180/32
                networks:
                  - Name: onprem-b
                    CidrBlock: 88.98.197.180/32

    - name: mediaconnect-bridge
      resources:
        - name: mediaconnect-bridge-a
          dependsOn:
            - key: placementArn
              source:
                name: mediaconnect-gateway-a
                apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
                kind: XGateway
                key: status.atProvider.id
          spec:
            apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
            kind: XBridge
            spec:
              forProvider:
                ingressGatewayBridge:
                  MaxOutputs: 2
                  MaxBitrate: 80000000
                sources:
                  - NetworkSource:
                      Name: onprem-a
                      MulticastIp: 224.0.0.0
                      NetworkName: onprem-a
                      Port: 3000
                      Protocol: rtp
                sourceFailoverConfig:
                  State: ENABLED
                  FailoverMode: FAILOVER
        - name: mediaconnect-bridge-b
          dependsOn:
            - key: placementArn
              source:
                name: mediaconnect-gateway-b
                apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
                kind: XGateway
                key: status.atProvider.id
          spec:
            apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
            kind: XBridge
            spec:
              forProvider:
                ingressGatewayBridge:
                  MaxOutputs: 2
                  MaxBitrate: 80000000
                sources:
                  - NetworkSource:
                      Name: onprem-b
                      MulticastIp: 224.0.0.0
                      NetworkName: onprem-b
                      Port: 3000
                      Protocol: rtp
                sourceFailoverConfig:
                  State: ENABLED
                  FailoverMode: FAILOVER

    - name: mediaconnect-flow
      resources:
        - name: mediaconnect-flow-a
          dependsOn:
            - key: source.GatewayBridgeSource.BridgeArn
              source:
                name: mediaconnect-bridge-a
                apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
                kind: XBridge
                key: status.atProvider.id
          spec:
            apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
            kind: XFlow
            spec:
              forProvider:
                flowSize: MEDIUM
        - name: mediaconnect-flow-b
          dependsOn:
            - key: source.GatewayBridgeSource.BridgeArn
              source:
                name: mediaconnect-bridge-a
                apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
                kind: XBridge
                key: status.atProvider.id
          spec:
            apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
            kind: XFlow
            spec:
              forProvider:
                flowSize: MEDIUM

    - name: medialive-network
      resources:
        - name: medialive-network-sg
          spec:
            apiVersion: medialive.aws.upbound.io/v1beta1
            kind: InputSecurityGroup
            spec:
              forProvider:
                whitelistRules:
                  - cidr: 88.98.197.180/32

    - name: medialive-multiplex
      resources:
        - name: medialive-multiplex-a
          dependsOn:
            - key: availabilityZones[0]
              source:
                name: mediaconnect-flow-a
                apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
                kind: XFlow
                key: status.atProvider.id
            - key: availabilityZones[1]
              source:
                name: mediaconnect-flow-b
                apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
                kind: XFlow
                key: status.atProvider.id
          spec:
            apiVersion: medialive.aws.upbound.io/v1beta2
            kind: Multiplex
            spec:
              forProvider:
                name: multiplex-a
                multiplexSettings:
                  maximumVideoBufferDelayMilliseconds: 1000
                  transportStreamBitrate: 1000000
                  transportStreamId: 1
                  transportStreamReservedBitrate: 1
                startMultiplex: true
        - name: medialive-multiplex-b
          dependsOn:
            - key: availabilityZones[0]
              source:
                name: mediaconnect-flow-a
                apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
                kind: XFlow
                key: "{{ (fromJson status.atProvider.properties).FlowAvailabilityZone }}"
            - key: availabilityZones[1]
              source:
                name: mediaconnect-flow-b
                apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
                kind: XFlow
                key: "{{ (fromJson status.atProvider.properties).FlowAvailabilityZone }}"
          spec:
            apiVersion: medialive.aws.upbound.io/v1beta2
            kind: Multiplex
            spec:
              forProvider:
                name: multiplex-b
                multiplexSettings:
                  maximumVideoBufferDelayMilliseconds: 1000
                  transportStreamBitrate: 1000000
                  transportStreamId: 1
                  transportStreamReservedBitrate: 1
                startMultiplex: true
