apiVersion: elemental.aws.livewyer.io/v1alpha1
kind: Workflow
metadata:
  name: workflow-demo
  labels:
    elemental.aws.livewyer.io/workflow: workflow-demo
spec:
  providerConfigRef:
    kind: ProviderConfig
    name: aws
  forProvider:
    region: us-east-1
  steps:
    - name: mediaconnect-flow
      resources:
        - name: mediaconnect-flow-a
          spec:
            apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
            kind: Flow
            spec:
              forProvider:
                flowSize: MEDIUM
                source:
                  Name: onprem-source-a
                  WhitelistCidr: 192.168.0.100/32
                  IngestPort: 3000
                  Protocol: rtp
                  MaxBitrate: 100000
        - name: mediaconnect-flow-b
          spec:
            apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
            kind: Flow
            spec:
              forProvider:
                flowSize: MEDIUM
                source:
                  Name: onprem-source-b
                  WhitelistCidr: 192.168.0.100/32
                  IngestPort: 4000
                  Protocol: rtp
                  MaxBitrate: 100000

    - name: medialive-network
      resources:
        - name: medialive-network-sg
          spec:
            apiVersion: medialive.aws.m.upbound.io/v1beta1
            kind: InputSecurityGroup
            spec:
              forProvider:
                whitelistRules:
                  - cidr: 192.168.0.100/32

    - name: medialive-input
      resources:
        - name: medialive-input-a1
          dependsOn:
            - key: mediaConnectFlows
              type: list
              subKey: flowArn
              source:
                name: mediaconnect-flow-a
                apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
                kind: Flow
                key: status.atProvider.id
            - key: mediaConnectFlows
              type: list
              subKey: flowArn
              source:
                name: mediaconnect-flow-b
                apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
                kind: Flow
                key: status.atProvider.id
          spec:
            apiVersion: medialive.aws.m.upbound.io/v1beta1
            kind: Input
            spec:
              forProvider:
                name: medialive-input-a1
                inputSecurityGroups:
                  - medialive-network-sg
                type: MEDIACONNECT
                roleArn: arn:aws:iam::123456789012:role/MediaLiveAccessRole
        - name: medialive-input-a2
          dependsOn:
            - key: mediaConnectFlows
              type: list
              subKey: flowArn
              source:
                name: mediaconnect-flow-a
                apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
                kind: Flow
                key: status.atProvider.id
            - key: mediaConnectFlows
              type: list
              subKey: flowArn
              source:
                name: mediaconnect-flow-b
                apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
                kind: Flow
                key: status.atProvider.id
          spec:
            apiVersion: medialive.aws.m.upbound.io/v1beta1
            kind: Input
            spec:
              forProvider:
                name: medialive-input-a2
                inputSecurityGroups:
                  - medialive-network-sg
                type: MEDIACONNECT
                roleArn: arn:aws:iam::123456789012:role/MediaLiveAccessRole
        - name: medialive-input-b
          dependsOn:
            - key: mediaConnectFlows
              type: list
              subKey: flowArn
              source:
                name: mediaconnect-flow-a
                apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
                kind: Flow
                key: status.atProvider.id
            - key: mediaConnectFlows
              type: list
              subKey: flowArn
              source:
                name: mediaconnect-flow-b
                apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
                kind: Flow
                key: status.atProvider.id
          spec:
            apiVersion: medialive.aws.m.upbound.io/v1beta1
            kind: Input
            spec:
              forProvider:
                name: medialive-input-b
                inputSecurityGroups:
                  - medialive-network-sg
                type: MEDIACONNECT
                roleArn: arn:aws:iam::123456789012:role/MediaLiveAccessRole
        - name: medialive-input-c
          dependsOn:
            - key: mediaConnectFlows
              type: list
              subKey: flowArn
              source:
                name: mediaconnect-flow-a
                apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
                kind: Flow
                key: status.atProvider.id
            - key: mediaConnectFlows
              type: list
              subKey: flowArn
              source:
                name: mediaconnect-flow-b
                apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
                kind: Flow
                key: status.atProvider.id
          spec:
            apiVersion: medialive.aws.m.upbound.io/v1beta1
            kind: Input
            spec:
              forProvider:
                name: medialive-input-c
                inputSecurityGroups:
                  - medialive-network-sg
                type: MEDIACONNECT
                roleArn: arn:aws:iam::123456789012:role/MediaLiveAccessRole

    - name: medialive-multiplex
      resources:
        - name: medialive-multiplex-a
          dependsOn:
            - key: availabilityZones
              type: list
              source:
                name: mediaconnect-flow-a
                apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
                kind: Flow
                key: status.atProvider.flowAvailabilityZone
            - key: availabilityZones
              type: list
              source:
                name: mediaconnect-flow-b
                apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
                kind: Flow
                key: status.atProvider.flowAvailabilityZone
          spec:
            apiVersion: medialive.aws.m.upbound.io/v1beta1
            kind: Multiplex
            spec:
              forProvider:
                name: multiplex-a
                multiplexSettings:
                  transportStreamBitrate: 1000000
                  transportStreamId: 1
                  maximumVideoBufferDelayMilliseconds: 800
                startMultiplex: true
        - name: medialive-multiplex-b
          dependsOn:
            - key: availabilityZones
              type: list
              source:
                name: mediaconnect-flow-a
                apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
                kind: Flow
                key: status.atProvider.flowAvailabilityZone
            - key: availabilityZones
              type: list
              source:
                name: mediaconnect-flow-b
                apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
                kind: Flow
                key: status.atProvider.flowAvailabilityZone
          spec:
            apiVersion: medialive.aws.m.upbound.io/v1beta1
            kind: Multiplex
            spec:
              forProvider:
                name: multiplex-b
                multiplexSettings:
                  transportStreamBitrate: 1000000
                  transportStreamId: 1
                  maximumVideoBufferDelayMilliseconds: 800
                startMultiplex: true

    - name: medialive-multiplex-program
      resources:
        - name: medialive-multiplex-program-a
          dependsOn:
            - key: multiplexId
              source:
                name: medialive-multiplex-a
                apiVersion: medialive.aws.m.upbound.io/v1beta1
                kind: Multiplex
                key: status.atProvider.id
          spec:
            apiVersion: medialive.aws.livewyer.io/v1alpha1
            kind: MultiplexProgram
            spec:
              forProvider:
                programName: program_a
                multiplexProgramSettings:
                  PreferredChannelPipeline: CURRENTLY_ACTIVE
                  ProgramNumber: 1
                  ServiceDescriptor:
                    ProviderName: sample-provider
                    ServiceName: service-a
                  VideoSettings:
                    ConstantBitrate: 100000
        - name: medialive-multiplex-program-b
          dependsOn:
            - key: multiplexId
              source:
                name: medialive-multiplex-b
                apiVersion: medialive.aws.m.upbound.io/v1beta1
                kind: Multiplex
                key: status.atProvider.id
          spec:
            apiVersion: medialive.aws.livewyer.io/v1alpha1
            kind: MultiplexProgram
            spec:
              forProvider:
                programName: program_b
                multiplexProgramSettings:
                  PreferredChannelPipeline: CURRENTLY_ACTIVE
                  ProgramNumber: 1
                  ServiceDescriptor:
                    ProviderName: sample-provider
                    ServiceName: service-b
                  VideoSettings:
                    ConstantBitrate: 100000

    - name: mediapackage-channel
      resources:
        - name: mediapackage-channel
          spec:
            apiVersion: mediapackage.aws.m.upbound.io/v1beta1
            kind: Channel
            spec:
              forProvider:
                channelId: mediapackage-channel
        - name: mediapackage-channel-endpoint
          spec:
            apiVersion: mediapackage.aws.livewyer.io/v1alpha1
            kind: OriginEndpoint
            spec:
              forProvider:
                channelId: mediapackage-channel
                origination: ALLOW
                cmafPackage:
                  HlsManifests:
                    - Id: hls-manifest

    - name: medialive-channel
      resources:
        - name: medialive-channel-a
          spec:
            apiVersion: medialive.aws.m.upbound.io/v1beta1
            kind: Channel
            spec:
              forProvider:
                name: medialive-channel-a
                channelClass: STANDARD
                roleArn: arn:aws:iam::123456789012:role/MediaLiveAccessRole
                inputSpecification:
                  codec: AVC
                  inputResolution: SD
                  maximumBitrate: MAX_10_MBPS
                inputAttachments:
                  - inputAttachmentName: medialive-input-a1
                    inputIdRef:
                      name: medialive-input-a1
                  - inputAttachmentName: medialive-input-a2
                    inputIdRef:
                      name: medialive-input-a2
                destinations:
                  - id: mediapackage
                    mediaPackageSettings:
                      - channelId: mediapackage-channel
                  - id: s3
                    settings:
                      - url: s3://output-bucket/live/recording-a
                      - url: s3://output-bucket/live/recording-b
                encoderSettings:
                  outputGroups:
                    - name: mediapackage-output
                      outputGroupSettings:
                        mediaPackageGroupSettings:
                          destination:
                            destinationRefId: mediapackage
                      outputs:
                        - outputName: mediapackage-output
                          videoDescriptionName: sample-video
                          audioDescriptionNames:
                            - sample-audio
                          outputSettings:
                            mediaPackageOutputSettings: {}
                    - name: s3-output
                      outputGroupSettings:
                        archiveGroupSettings:
                          - destination:
                              destinationRefId: s3
                      outputs:
                        - outputName: s3-output
                          videoDescriptionName: sample-video
                          audioDescriptionNames:
                            - sample-audio
                          outputSettings:
                            archiveOutputSettings:
                              containerSettings:
                                m2tsSettings: {}
                              extension: m2ts
                              nameModifier: _1
                  timecodeConfig:
                    source: EMBEDDED
                  videoDescriptions:
                    - name: sample-video
                      height: 640
                      width: 480
                      codecSettings:
                        h265Settings:
                          level: H265_LEVEL_AUTO
                          framerateDenominator: 1
                          framerateNumerator: 24
                  audioDescriptions:
                    - name: sample-audio
                      audioSelectorName: sample-audio
        - name: medialive-channel-b
          dependsOn:
            - key: destinations
              type: list
              subKey: multiplexSettings.multiplexId
              subKeyPatchMethod: merge
              source:
                name: medialive-multiplex-a
                apiVersion: medialive.aws.m.upbound.io/v1beta1
                kind: Multiplex
                key: status.atProvider.id
          spec:
            apiVersion: medialive.aws.m.upbound.io/v1beta1
            kind: Channel
            spec:
              forProvider:
                name: medialive-channel-b
                channelClass: STANDARD
                roleArn: arn:aws:iam::123456789012:role/MediaLiveAccessRole
                inputSpecification:
                  codec: AVC
                  inputResolution: SD
                  maximumBitrate: MAX_10_MBPS
                inputAttachments:
                  - inputAttachmentName: medialive-input-b
                    inputIdRef:
                      name: medialive-input-b
                destinations:
                  - id: multiplex-a
                    multiplexSettings:
                      programName: program_a
                encoderSettings:
                  outputGroups:
                    - name: multiplex-a
                      outputGroupSettings:
                        multiplexGroupSettings: {}
                      outputs:
                        - outputName: multiplex-a
                          videoDescriptionName: sample-video
                          audioDescriptionNames:
                            - sample-audio
                          outputSettings:
                            multiplexOutputSettings:
                              destination:
                                destinationRefId: multiplex-a
                  timecodeConfig:
                    source: EMBEDDED
                  videoDescriptions:
                    - name: sample-video
                      height: 640
                      width: 480
                      codecSettings:
                        h265Settings:
                          level: H265_LEVEL_AUTO
                          framerateDenominator: 1
                          framerateNumerator: 24
                  audioDescriptions:
                    - name: sample-audio
                      audioSelectorName: sample-audio
        - name: medialive-channel-c
          dependsOn:
            - key: destinations
              type: list
              subKey: multiplexSettings.multiplexId
              subKeyPatchMethod: merge
              source:
                name: medialive-multiplex-b
                apiVersion: medialive.aws.m.upbound.io/v1beta1
                kind: Multiplex
                key: status.atProvider.id
          spec:
            apiVersion: medialive.aws.m.upbound.io/v1beta1
            kind: Channel
            spec:
              forProvider:
                name: medialive-channel-c
                channelClass: STANDARD
                roleArn: arn:aws:iam::123456789012:role/MediaLiveAccessRole
                inputSpecification:
                  codec: AVC
                  inputResolution: SD
                  maximumBitrate: MAX_10_MBPS
                inputAttachments:
                  - inputAttachmentName: medialive-input-c
                    inputIdRef:
                      name: medialive-input-c
                destinations:
                  - id: multiplex-b
                    multiplexSettings:
                      programName: program_b
                encoderSettings:
                  outputGroups:
                    - name: multiplex-b
                      outputGroupSettings:
                        multiplexGroupSettings: {}
                      outputs:
                        - outputName: multiplex-b
                          videoDescriptionName: sample-video
                          audioDescriptionNames:
                            - sample-audio
                          outputSettings:
                            multiplexOutputSettings:
                              destination:
                                destinationRefId: multiplex-b
                  timecodeConfig:
                    source: EMBEDDED
                  videoDescriptions:
                    - name: sample-video
                      height: 640
                      width: 480
                      codecSettings:
                        h265Settings:
                          level: H265_LEVEL_AUTO
                          framerateDenominator: 1
                          framerateNumerator: 24
                  audioDescriptions:
                    - name: sample-audio
                      audioSelectorName: sample-audio
