apiVersion: elemental.aws.livewyer.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-usecase-1
  labels:
    elemental.aws.livewyer.io/event: workflow-usecase-1
spec:
  steps:
    - name: medialive-network
      resources:
        - name: medialive-network
          spec:
            apiVersion: medialive.aws.livewyer.io/v1alpha1
            kind: Network
            spec:
              forProvider:
                ipPools:
                  - Cidr: "{{ network }}"
        - name: medialive-network-sg
          spec:
            apiVersion: medialive.aws.upbound.io/v1beta1
            kind: InputSecurityGroup
            spec:
              forProvider:
                whitelistRules:
                  - cidr: "{{ network }}"

    - name: medialive-input
      resources:
        - name: medialive-input-a
          spec:
            apiVersion: medialive.aws.upbound.io/v1beta2
            kind: Input
            spec:
              forProvider:
                name: medialive-input-a
                inputSecurityGroupsRefs:
                  - name: medialive-network-sg
                type: RTP_PUSH
        - name: medialive-input-b
          spec:
            apiVersion: medialive.aws.upbound.io/v1beta2
            kind: Input
            spec:
              forProvider:
                name: medialive-input-b
                inputSecurityGroupsRefs:
                  - name: medialive-network-sg
                type: RTP_PUSH

    - name: mediapackage-channel
      resources:
        - name: mediapackage-channel
          spec:
            apiVersion: mediapackage.aws.upbound.io/v1beta1
            kind: Channel
            spec:
              forProvider:
                channelId: mediapackage-channel
        - name: mediapackage-channel-endpoint
          spec:
            apiVersion: mediapackage.aws.livewyer.io/v1alpha1
            kind: OriginEndpoint
            spec:
              forProvider:
                channelId: mediapackage-channel
                origination: ALLOW
                cmafPackage:
                  HlsManifests:
                    - Id: hls-manifest

    - name: medialive-channel
      resources:
        - name: medialive-channel
          spec:
            apiVersion: medialive.aws.upbound.io/v1beta2
            kind: Channel
            spec:
              forProvider:
                name: medialive-channel
                channelClass: SINGLE_PIPELINE
                roleArn: "{{ iamRole }}"
                inputSpecification:
                  codec: AVC
                  inputResolution: SD
                  maximumBitrate: MAX_10_MBPS
                inputAttachments:
                  - inputAttachmentName: medialive-input-a
                    inputIdRef:
                      name: medialive-input-a
                  - inputAttachmentName: medialive-input-b
                    inputIdRef:
                      name: medialive-input-b
                destinations:
                  - id: mediapackage
                    mediaPackageSettings:
                      - channelId: mediapackage-channel
                encoderSettings:
                  audioDescriptions:
                    - name: sample-audio
                      audioSelectorName: default
                  videoDescriptions:
                    - name: sample-video
                      height: 480
                      width: 640
                      codecSettings:
                        h265Settings:
                          level: H265_LEVEL_AUTO
                          framerateDenominator: 1
                          framerateNumerator: 24
                  outputGroups:
                    - outputGroupSettings:
                        mediaPackageGroupSettings:
                          destination:
                            destinationRefId: mediapackage
                      outputs:
                        - outputName: mediapackage
                          audioDescriptionNames:
                            - sample-audio
                          videoDescriptionName: sample-video
                          outputSettings:
                            mediaPackageOutputSettings: {}
                  timecodeConfig:
                    source: EMBEDDED
