apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xjobtemplate.mediaconvert.aws.livewyer.io
spec:
  group: mediaconvert.aws.livewyer.io
  names:
    kind: XJobTemplate
    plural: xjobtemplates
  claimNames:
    kind: JobTemplate
    plural: jobtemplates
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    name:
                      type: string
                      description: "The name of the job template."
                    category:
                      type: string
                      description: "An optional category you create to organize your job templates."
                    description:
                      type: string
                      description: "An optional description you create for each job template."
                    priority:
                      type: integer
                      description: "Specify the relative priority for this job. In any given queue, the service begins processing the job with the highest value first. Acceptable values: -50 to 50."
                      minimum: -50
                      maximum: 50
                    queue:
                      type: string
                      description: "Optional. The queue that jobs created from this template are assigned to. If you don't specify this, jobs will be sent to the default queue."
                    statusUpdateInterval:
                      type: string
                      description: "Specify how often MediaConvert sends STATUS_UPDATE events to Amazon CloudWatch Events. Set the interval, in seconds, between status updates."
                      enum:
                        - "SECONDS_10"
                        - "SECONDS_12"
                        - "SECONDS_15"
                        - "SECONDS_20"
                        - "SECONDS_30"
                        - "SECONDS_60"
                        - "SECONDS_120"
                        - "SECONDS_180"
                        - "SECONDS_240"
                        - "SECONDS_300"
                        - "SECONDS_360"
                        - "SECONDS_420"
                        - "SECONDS_480"
                        - "SECONDS_540"
                        - "SECONDS_600"
                    accelerationSettings:
                      type: object
                      description: "Accelerated transcoding can significantly speed up jobs with long, visually complex content. Outputs that use this feature incur pro-tier pricing."
                      properties:
                        mode:
                          type: string
                          description: "Specify the conditions when the service will run your job with accelerated transcoding."
                          enum:
                            - "DISABLED"
                            - "ENABLED"
                            - "PREFERRED"
                      required:
                        - mode
                      additionalProperties: false
                    hopDestinations:
                      type: array
                      description: "Optional list of hop destinations."
                      items:
                        type: object
                        properties:
                          priority:
                            type: integer
                            description: "Optional. When you set up a job to use queue hopping, you can specify a different relative priority for the job in the destination queue."
                            minimum: -50
                            maximum: 50
                          queue:
                            type: string
                            description: "Optional unless the job is submitted on the default queue. When you set up a job to use queue hopping, you can specify a destination queue."
                          waitMinutes:
                            type: integer
                            description: "Required for setting up a job template for MediaConvert queue hopping. Minimum wait time in minutes until the job can hop to the destination queue."
                            minimum: 1
                            maximum: 1440
                        additionalProperties: false
                    settingsJson:
                      type: object
                      description: "Specify, in JSON format, the transcoding job settings for this job template. This specification must be formed in a particular way that conforms to AWS Elemental MediaConvert job validation. For more information about creating a job template model for the SettingsJson property, see the AWS Elemental MediaConvert User Guide."
                      additionalProperties: true
                      properties:
                        timecodeConfig:
                          type: object
                          description: "These settings control how the service handles timecodes throughout the job."
                          additionalProperties: true
                        inputs:
                          type: array
                          description: "Use inputs to define the source files used in your transcoding job."
                          items:
                            type: object
                            additionalProperties: true
                        outputGroups:
                          type: array
                          description: "MediaConvert places outputs in the same output group container."
                          items:
                            type: object
                            additionalProperties: true
                        adAvailOffset:
                          type: integer
                          description: "When specified, this offset (in milliseconds) is added to the input Ad Avail PTS time."
                        availBlanking:
                          type: object
                          description: "Settings for ad avail blanking."
                          additionalProperties: true
                        esam:
                          type: object
                          description: "Settings for Event Signaling And Messaging (ESAM)."
                          additionalProperties: true
                        motionImageInserter:
                          type: object
                          description: "Overlay motion graphics on top of your video."
                          additionalProperties: true
                        nielsenConfiguration:
                          type: object
                          description: "Settings for your Nielsen configuration."
                          additionalProperties: true
                        nielsenNonLinearWatermark:
                          type: object
                          description: "Ignore these settings unless you are using Nielsen non-linear watermarking."
                          additionalProperties: true
                    region:
                      type: string
                      description: "AWS region where the job template will be created."
                      default: "us-east-1"
                    tags:
                      type: object
                      description: "A map of tags to assign to the resource."
                      additionalProperties:
                        type: string
                  required:
                    - name
                    - settingsJson
                  additionalProperties: false
                deletionPolicy:
                  type: string
                  enum:
                    - Delete
                    - Orphan
                  default: Delete
                  description: "DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted."
                managementPolicies:
                  type: array
                  items:
                    type: string
                    enum:
                      - "*"
                      - Create
                      - Update
                      - Delete
                      - LateInitialize
                      - Observe
                  default: ["*"]
                  description: "ManagementPolicies specify the array of actions Crossplane is allowed to take on the managed and external resources."
                providerConfigRef:
                  type: object
                  properties:
                    name:
                      type: string
                  required:
                    - name
                  description: "ProviderConfigReference specifies how the provider that will be used to create, observe, update, and delete this managed resource should be configured."
                publishConnectionDetailsTo:
                  type: object
                  properties:
                    name:
                      type: string
                    configRef:
                      type: object
                      properties:
                        name:
                          type: string
                      required:
                        - name
                    metadata:
                      type: object
                      properties:
                        labels:
                          type: object
                          additionalProperties:
                            type: string
                        annotations:
                          type: object
                          additionalProperties:
                            type: string
                        type:
                          type: array
                          items:
                            type: string
                  required:
                    - name
                  description: "PublishConnectionDetailsTo specifies the connection secret config which contains a name, metadata and a reference to secret store config to which any connection details for this managed resource should be written."
                writeConnectionSecretsToNamespace:
                  type: string
                  description: "WriteConnectionSecretsToNamespace specifies the namespace in which the connection secrets of this managed resource should be written."
              required:
                - parameters
              additionalProperties: false
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      lastTransitionTime:
                        type: string
                        format: date-time
                      message:
                        type: string
                      reason:
                        type: string
                      status:
                        type: string
                      type:
                        type: string
                    required:
                      - lastTransitionTime
                      - reason
                      - status
                      - type
                connectionDetails:
                  type: object
                  properties:
                    lastPublishedTime:
                      type: string
                      format: date-time
                arn:
                  type: string
                  description: "The Amazon Resource Name (ARN) of the job template."
                name:
                  type: string
                  description: "The name of the job template."
                type:
                  type: string
                  description: "A system-generated string that identifies the type of job template."
                  enum:
                    - "SYSTEM"
                    - "CUSTOM"
          required:
            - spec
      additionalPrinterColumns:
        - name: READY
          type: string
          jsonPath: ".status.conditions[?(@.type=='Ready')].status"
        - name: SYNCED
          type: string
          jsonPath: ".status.conditions[?(@.type=='Synced')].status"
        - name: EXTERNAL-NAME
          type: string
          jsonPath: ".metadata.annotations.crossplane\\.io/external-name"
        - name: CATEGORY
          type: string
          jsonPath: ".spec.parameters.category"
        - name: PRIORITY
          type: integer
          jsonPath: ".spec.parameters.priority"
        - name: AGE
          type: date
          jsonPath: ".metadata.creationTimestamp"
