apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: flow.mediaconnect.aws.livewyer.io
spec:
  compositeTypeRef:
    apiVersion: mediaconnect.aws.livewyer.io/v1alpha1
    kind: Flow
  mode: Pipeline
  pipeline:
    - step: go-templating
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{ $id := .observed.composite.resource.metadata.name -}}
            {{ $spec := .observed.composite.resource.spec.forProvider -}}
            {{ $status := getCompositeResource . | getResourceCondition "atProvider" }}

            apiVersion: cloudcontrol.aws.m.upbound.io/v1beta1
            kind: Resource
            metadata:
              name: {{ $id }}
              namespace: {{ default "default" $.observed.composite.resource.metadata.namespace }}
              annotations:
                {{ setResourceNameAnnotation (printf "flow.mediaconnect.aws.livewyer.io/%s" $id) }}
              labels:
                mediaconnect.aws.livewyer.io/flow: {{ $id }}
            spec:
            {{- if .observed.composite.resource.spec.providerConfigRef }}
              providerConfigRef:
            {{ toYaml .observed.composite.resource.spec.providerConfigRef | indent 4 }}
            {{- end }}
            {{- if .observed.composite.resource.spec.deletionPolicy }}
              deletionPolicy: {{ .observed.composite.resource.spec.deletionPolicy }}
            {{- end }}
            {{- if .observed.composite.resource.spec.managementPolicies }}
              managementPolicies:
            {{ toYaml .observed.composite.resource.spec.managementPolicies | indent 4 }}
            {{- end }}
            {{- if .observed.composite.resource.spec.publishConnectionDetailsTo }}
              publishConnectionDetailsTo:
                {{ toYaml .observed.composite.resource.spec.publishConnectionDetailsTo | indent 4 }}
            {{- end }}
            {{- if .observed.composite.resource.spec.writeConnectionSecretsToNamespace }}
              writeConnectionSecretsToNamespace: {{ .observed.composite.resource.spec.writeConnectionSecretsToNamespace }}
            {{- end }}
              forProvider:
                region: {{ $spec.region }}
                typeName: AWS::MediaConnect::Flow
                desiredState: |-
                  {
                    "Name": "{{ $id }}",
                    "Source": {{ toJson $spec.source }}
                    {{- if $spec.availabilityZone }},
                    "AvailabilityZone": "{{ $spec.availabilityZone }}"
                    {{- end }}
                    {{- if $spec.sourceFailoverConfig }},
                    "SourceFailoverConfig": {{ toJson $spec.sourceFailoverConfig }}
                    {{- end }}
                    {{- if $spec.sourceMonitoringConfig }}
                    "SourceMonitoringConfig": {{ toJson $spec.sourceMonitoringConfig }}
                    {{- end }}
                    {{- if $spec.mediaStreams }},
                    "MediaStreams": {{ toJson $spec.mediaStreams }}
                    {{- end }}
                    {{- if $spec.vpcInterfaces }},
                    "VpcInterfaces": {{ toJson $spec.vpcInterfaces }}
                    {{- end }}
                    {{- if $spec.maintenance }},
                    "Maintenance": {{ toJson $spec.maintenance }}
                    {{- end }}
                    {{- if $spec.tags }},
                    "Tags": {{ toJson $spec.tags }}
                    {{- end }}
                  }

            ---

            {{ $awscc := getComposedResource . (printf "flow.mediaconnect.aws.livewyer.io/%s" $id) }}
            apiVersion: {{ .observed.composite.resource.apiVersion }}
            kind: {{ .observed.composite.resource.kind }}
            metadata:
              labels:
                mediaconnect.aws.livewyer.io/flow: {{ $id }}
            status:
              {{- $properties := dict }}
              {{- $properties := (fromJson (default "{}" $awscc.status.atProvider.properties)) }}
              atProvider: {{ toJson (merge $awscc.status.atProvider (dict "flowAvailabilityZone" (dig "FlowAvailabilityZone" "" $properties))) }}

    - step: go-templating-svc
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{ $id := .observed.composite.resource.metadata.name -}}
            {{ $awscc := getComposedResource . (printf "flow.mediaconnect.aws.livewyer.io/%s" $id) }}

            {{ if and (default true $.observed.composite.resource.spec.exportEndpointAsService) (dig "Source" "IngestIp" "" (fromJson (default "{}" $awscc.status.atProvider.properties))) (dig "Source" "IngestPort" "" (fromJson (default "{}" $awscc.status.atProvider.properties))) }}
            apiVersion: kubernetes.m.crossplane.io/v1alpha1
            kind: Object
            metadata:
              annotations:
                {{ setResourceNameAnnotation (printf "svc.flow.mediaconnect.aws.livewyer.io/%s" $id) }}
              name: {{ $id }}
              namespace: {{ default "default" $.observed.composite.resource.metadata.namespace }}
              labels:
                mediaconnect.aws.livewyer.io/flow: {{ $id }}
            spec:
              forProvider:
                manifest:
                  apiVersion: v1
                  kind: Service
                  metadata:
                    name: {{ $id }}
                    namespace: {{ default "default" $.observed.composite.resource.metadata.namespace }}
                    labels:
                      mediaconnect.aws.livewyer.io/flow: {{ $id }}
                  spec:
                    type: ExternalName
                    externalName: {{ dig "Source" "IngestIp" "" (fromJson (default "{}" $awscc.status.atProvider.properties)) }}
                    ports:
                      - name: tcp
                        port: {{ dig "Source" "IngestPort" "" (fromJson (default "{}" $awscc.status.atProvider.properties)) }}
                        protocol: TCP
                        targetPort: {{ dig "Source" "IngestPort" "" (fromJson (default "{}" $awscc.status.atProvider.properties)) }}
                      - name: udp
                        port: {{ dig "Source" "IngestPort" "" (fromJson (default "{}" $awscc.status.atProvider.properties)) }}
                        protocol: UDP
                        targetPort: {{ dig "Source" "IngestPort" "" (fromJson (default "{}" $awscc.status.atProvider.properties)) }}
                  {{ end }}

    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: function-auto-ready
